// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK8_2vVz1qV6_5KrACDfjiZdaLpF8LORg',
    appId: '1:197919928248:web:f1f235a3b189b269b6294d',
    messagingSenderId: '197919928248',
    projectId: 'practical-test-af',
    authDomain: 'practical-test-af.firebaseapp.com',
    storageBucket: 'practical-test-af.appspot.com',
    measurementId: 'G-Q69GL5FHJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0DmpkXXbG0nIHWM1k953P58BeN8a4W8',
    appId: '1:197919928248:android:0d4fb698bfc9f6acb6294d',
    messagingSenderId: '197919928248',
    projectId: 'practical-test-af',
    storageBucket: 'practical-test-af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbp55Cq17cgp-2hwEwVhIEShoAvW-120',
    appId: '1:197919928248:ios:332b6bb5739cceacb6294d',
    messagingSenderId: '197919928248',
    projectId: 'practical-test-af',
    storageBucket: 'practical-test-af.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbp55Cq17cgp-2hwEwVhIEShoAvW-120',
    appId: '1:197919928248:ios:758686b7b846eff7b6294d',
    messagingSenderId: '197919928248',
    projectId: 'practical-test-af',
    storageBucket: 'practical-test-af.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
